// migration/app/campaign/list/campaign-list.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Store } from '@ngrx/store';
import { TranslocoModule, TranslocoService } from '@jsverse/transloco';
import { takeUntil } from 'rxjs/operators';

import { DestroyableComponent } from '../shared/base.component';
import { HasPermissionDirective } from '../shared/has-permission.directive';
import { FeatureFlagDirective } from '../feature-flags/feature-flag.directive';
import { CampaignActions } from '../store/campaign.actions';
import { selectActiveCampaigns, selectLoading } from '../store/campaign.selectors';

@Component({
  selector: 'app-campaign-list',
  standalone: true,
  imports: [CommonModule, RouterLink, TranslocoModule, HasPermissionDirective, FeatureFlagDirective],
  templateUrl: './campaign-list.component.html',
})
export class CampaignListComponent extends DestroyableComponent implements OnInit {
  private store = inject(Store);
  private transloco = inject(TranslocoService);

  readonly campaigns = this.store.select(selectActiveCampaigns);
  readonly loading = this.store.select(selectLoading);

  ngOnInit(): void {
    this.store.dispatch(CampaignActions.load());
    this.transloco
      .selectTranslate('campaign.title')
      .pipe(takeUntil(this.destroy$))
      .subscribe(title => (document.title = title));
  }

  select(id: number): void {
    this.store.dispatch(CampaignActions.select({ id }));
  }
}

<section class="campaign-list" *transloco="let t; scope: 'campaign'">
  <div class="d-flex justify-content-between align-items-center mb-3">
    <h1>{{ t('campaign.title') }}</h1>
    <a *appHasPermission="'campaign:edit'" class="btn btn-primary" routerLink="/campaign/new">
      {{ t('campaign.new') }}
    </a>
  </div>

  @if (loading | async) {
    <p class="text-muted">{{ t('campaign.loading') }}</p>
  } @else {
    @for (campaign of campaigns | async; track campaign.id) {
      <button type="button" class="list-group-item list-group-item-action" (click)="select(campaign.id)">
        <span class="fw-bold">{{ campaign.name }}</span>
        <span class="badge bg-secondary ms-2">{{ campaign.budget | number }}</span>
        <span *appFeatureFlag="'campaigns-v2'" class="badge bg-info ms-2">v2</span>
      </button>
    } @empty {
      <p class="text-muted">{{ t('campaign.empty') }}</p>
    }
  }
</section>

// migration/app/campaign/list/campaign-list.tsx
import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import {
  CampaignActions,
  useActiveCampaigns,
  useCampaignLoading,
  useStore,
} from '../hooks/use-store';
import { useTranslocoService } from '../hooks/use-transloco';

export function CampaignListComponent() {
  const store = useStore();
  const transloco = useTranslocoService();
  const campaigns = useActiveCampaigns();
  const loading = useCampaignLoading();
  const { t } = useTranslation('campaign');

  function select(id: number): void {
    store.dispatch(CampaignActions.select(id));
  }

  useEffect(() => {
    store.dispatch(CampaignActions.load());
    const sub = transloco
      .selectTranslate('title')
      .pipe()
      .subscribe((title: string) => {
        document.title = title;
      });
    return () => sub.unsubscribe();
  }, [store, transloco]);

  return (
    <section className="campaign-list">
      <div className="d-flex justify-content-between align-items-center mb-3">
        <h1>{t('title')}</h1>
        <Link className="btn btn-primary" to="/campaign/new">
          {t('new')}
        </Link>
      </div>

      {loading ? (
        <p className="text-muted">{t('loading')}</p>
      ) : campaigns.length === 0 ? (
        <p className="text-muted">{t('empty')}</p>
      ) : (
        <div className="list-group">
          {campaigns.map((campaign) => (
            <button
              key={campaign.id}
              type="button"
              className="list-group-item list-group-item-action"
              onClick={() => select(campaign.id)}
            >
              <span className="fw-bold">{campaign.name}</span>
              <span className="badge bg-secondary ms-2">{campaign.budget.toLocaleString()}</span>
            </button>
          ))}
        </div>
      )}
    </section>
  );
}
