// migration/app/campaign/edit/campaign-edit.tsx
import { useEffect } from 'react';
import { useForm } from 'react-hook-form';

export interface CampaignEditComponentProps {
  campaign?: ICampaign | null;
}

export function CampaignEditComponent({ campaign }: CampaignEditComponentProps) {
  const fb = useFormBuilder(); // MIGRATION_TODO(di): was inject(FormBuilder); create this hook (or a context provider) for the ported service.
  const store = useStore(); // MIGRATION_TODO(di): was inject(Store); create this hook (or a context provider) for the ported service.
  const slugInvalid = (() => {
    const control = form.controls.slug;
    return control.invalid && control.touched;
  })(); // MIGRATION_TODO(derived): was computed()/getter; confirm no memo needed — reactive-form `form.controls` has no direct react-hook-form equivalent — port by hand (piped `.valueChanges` -> `watch(cb)` inside a `useEffect`, `.statusChanges` -> `formState`, `.controls`/`.get()` -> `register`/`getValues`)
  const form = useForm<{ name: string; slug: string; budget: number; active: boolean }>({
    defaultValues: {
      name: '',
      slug: '',
      budget: 0,
      active: true,
    },
  });
  // MIGRATION_TODO(forms): `form` was an Angular reactive form. Template bindings ([formGroup]/(ngSubmit)/formControlName, `.get()`/`.value`/`.invalid` reads) and method-body ops (`.value`->`getValues()`, `.patchValue/.setValue(v)`->`reset(v)`, `.get('x')?.setValue(v)`-> `setValue('x', v)`, `.markAllAsTouched()`->`trigger()`) are lowered. Verify the `patchValue`->`reset` sites: RHF `reset` replaces all fields and clears dirty/touched state, whereas Angular `patchValue` was a partial merge that preserved it.
  // MIGRATION_TODO(forms-validators): port Angular validators to a resolver (zod/yup + `useForm({ resolver })`) — name: [Validators.required, Validators.maxLength(60)]; slug: [Validators.required, slugValidator()]; budget: [Validators.required, Validators.min(0)]
  function submit(): void {
    if (!form.formState.isValid) {
      form.trigger();
      return;
    }
    const value = form.getRawValue();
    store.dispatch(
      CampaignActions.create({
        campaign: {
          id: null,
          name: value.name!,
          slug: value.slug!,
          budget: value.budget!,
          active: value.active!,
          tenantId: '',
        },
      }),
    );
  }
  // MIGRATION_TODO(effect): ngOnInit -> mount effect; verify deps ([])
  useEffect(() => {
    if (campaign) {
      form.reset(campaign);
    }
  }, []);

  return (
    <>{/* MIGRATION_TODO: structural directive/*transloco not deterministically supported */}</>
  );
}

// fixtures/jhipster-ng17-fixture/retrofit/campaign/edit/campaign-edit.component.ts
import { Component, inject, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Store } from '@ngrx/store';
import { TranslocoModule } from '@jsverse/transloco';

import { ICampaign } from '../campaign.model';
import { CampaignActions } from '../store/campaign.actions';
import { slugValidator } from '../validators/slug.validator';

@Component({
  selector: 'app-campaign-edit',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, TranslocoModule],
  templateUrl: './campaign-edit.component.html',
})
export class CampaignEditComponent implements OnInit {
  private fb = inject(FormBuilder);
  private store = inject(Store);

  /** Resolved by `campaignResolver` and bound via `withComponentInputBinding`. */
  @Input() campaign: ICampaign | null = null;

  form = this.fb.group({
    name: ['', [Validators.required, Validators.maxLength(60)]],
    slug: ['', [Validators.required, slugValidator()]],
    budget: [0, [Validators.required, Validators.min(0)]],
    active: [true],
  });

  ngOnInit(): void {
    if (this.campaign) {
      this.form.patchValue(this.campaign);
    }
  }

  get slugInvalid(): boolean {
    const control = this.form.controls.slug;
    return control.invalid && control.touched;
  }

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    const value = this.form.getRawValue();
    this.store.dispatch(
      CampaignActions.create({
        campaign: { id: null, name: value.name!, slug: value.slug!, budget: value.budget!, active: value.active!, tenantId: '' },
      }),
    );
  }
}
